### ISSUE TITLE
Unable to pass parameters

### ISSUE THREAD

**Issue by wtf-boy** [jxnkwlp/JsonStringLocalizerSample#1]
![image](https://user-images.githubusercontent.com/11848141/41597598-7398cade-7400-11e8-800c-03d9de87d90e.png)
![image](https://user-images.githubusercontent.com/11848141/41597672-afce524e-7400-11e8-9a8b-4b925c45714f.png)

**Comment by jxnkwlp** [comment]
i  do not why is happy. 
i read the source code , in the view file  `HtmlLocalizer`  it use `ToHtmlString` to format arguments , not `IStringLocalizer` .

`public virtual LocalizedHtmlString this[string name, params object[] arguments]
	{
		get
		{
			if (name == null)
			{
				throw new ArgumentNullException("name");
			}
			return ToHtmlString(_localizer[name], arguments);
		}
	}`
